"""add_security_to_exam_record

Revision ID: a1b2c3d4e5f8
Revises: 1da99fba2131
Create Date: 2026-08-06 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f8'
down_revision: Union[str, None] = '1da99fba2131'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_record', sa.Column('exam_code', sa.String(length=50), nullable=True))
    op.add_column('exam_record', sa.Column('participant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_exam_record_exam_code'), 'exam_record', ['exam_code'])
    op.create_index(op.f('ix_exam_record_participant_id'), 'exam_record', ['participant_id'])
    op.create_foreign_key(
        'fk_exam_record_participant_id', 'exam_record', 'exam_participant',
        ['participant_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_exam_record_participant_id', 'exam_record', type_='foreignkey')
    op.drop_index(op.f('ix_exam_record_participant_id'), table_name='exam_record')
    op.drop_index(op.f('ix_exam_record_exam_code'), table_name='exam_record')
    op.drop_column('exam_record', 'participant_id')
    op.drop_column('exam_record', 'exam_code')
    # ### end Alembic commands ###
