"""merge_s43b_heads

Revision ID: b2c3d4e5f6a7
Revises: a1b2c3d4e5f8, c3d4e5f6a7b8
Create Date: 2026-08-06 10:05:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2c3d4e5f6a7'
down_revision: Union[str, None] = ('a1b2c3d4e5f8', 'c3d4e5f6a7b8')
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # This is a merge revision, no upgrade logic needed
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # This is a merge revision, no downgrade logic needed
    pass
    # ### end Alembic commands ###
