"""add_exam_monitor_summary

Revision ID: g7h8i9j0k1l2
Revises: f1a2b3c4d5e6
Create Date: 2026-08-18 16:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'g7h8i9j0k1l2'
down_revision: Union[str, None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # SQLite doesn't support CREATE TYPE for enum, so we skip it
    # The Enum will be created as a CHECK constraint by SQLAlchemy on SQLite
    
    op.create_table('exam_monitor_summary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exam_record_id', sa.Integer(), nullable=False),
    sa.Column('leave_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_duration', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('risk_level', sa.Enum('normal', 'low', 'medium', 'high', name='risk_level'), server_default=sa.text("'normal'"), nullable=False),
    sa.Column('detail_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['exam_record_id'], ['exam_record.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_record_id')
    )
    op.create_index(op.f('ix_exam_monitor_summary_exam_record_id'), 'exam_monitor_summary', ['exam_record_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exam_monitor_summary_exam_record_id'), table_name='exam_monitor_summary')
    op.drop_table('exam_monitor_summary')
    # ### end Alembic commands ###
